# Generated by Django 5.0.4 on 2024-05-13 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pmsApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelTable(
            name='customuser',
            table=None,
        ),
    ]
