# Generated by Django 5.0.4 on 2024-05-14 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmsApp', '0002_alter_customuser_options_alter_customuser_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('admin', 'admin'), ('hod', 'hod'), ('manager', 'institute_manager')], max_length=30),
        ),
    ]
