# Generated by Django 5.0.4 on 2024-05-14 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pmsApp', '0003_alter_customuser_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
    ]
